In [8]:
import numpy as np
print(np.__version__)


2.3.5


In [9]:
# 20
import numpy as np
import pandas as pd
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

df = pd.DataFrame({
'Country': ['Philippines','USA','UK','Canada','Germany'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})

top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max'])
print(top_countries)

                 mean     max
Country                      
Canada        43006.0   43006
Germany      120003.0  120003
Philippines  135222.0  135222
UK            66445.0   66445
USA          140606.0  140606


In [10]:
# 19
import numpy as np
import pandas as pd
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
threshold = 110000

df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')
print(df)

   ConvertedComp HighPay
0         135222     Yes
1         140606     Yes
2          66445      No
3          43006      No
4         120003     Yes


In [11]:
# 18
import numpy as np
import pandas as pd
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

df = pd.DataFrame({
'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})

summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).reset_index()
print(summary)

    EdLevel      mean    median           std
0  Bachelor   89114.0   89114.0  65206.558934
1    Master  130304.5  130304.5  14568.521013
2       PhD   66445.0   66445.0           NaN


In [12]:
# 17
import numpy as np
import pandas as pd
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

df = pd.DataFrame({
'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5),
'ConvertedComp': np.random.randint(40000, 150000, 5)
})

corr_matrix = df.corr()
print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000       0.983647
ConvertedComp      0.983647       1.000000


In [13]:
# 16
import numpy as np
import pandas as pd
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
df['LogComp'] = np.log(df['ConvertedComp'])

print(df)

   ConvertedComp    LogComp
0         135222  11.814673
1         140606  11.853717
2          66445  11.104130
3          43006  10.669095
4         120003  11.695272


In [14]:
# 15
import numpy as np
import pandas as pd
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})

bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']

df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

   ConvertedComp   Bracket
0         135222  100-150k
1         140606  100-150k
2          66445   50-100k
3          43006     0-50k
4         120003  100-150k


In [15]:
# 14
import numpy as np
import pandas as pd
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

df = pd.DataFrame({
 'Name':[STUDENT_NAME]*5,
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})

high_exp = df[df['YearsCodePro']>STUDENT_ID%10]
print(high_exp)

             Name  YearsCodePro
0  Gabriel Moreno            22
1  Gabriel Moreno            10
2  Gabriel Moreno            19
3  Gabriel Moreno            13


In [16]:
# 13
import numpy as np
import pandas as pd
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

df = pd.DataFrame({
 'Country': ['Philippines','USA','UK','Canada','Germany'],
 'ConvertedComp': np.random.randint(40000, 150000, 5)
})

top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)

       Country  ConvertedComp
1          USA         140606
0  Philippines         135222
4      Germany         120003
2           UK          66445
3       Canada          43006


In [17]:
# 12
import numpy as np
import pandas as pd
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

df = pd.DataFrame({
'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})

avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)

EdLevel
Bachelor     89114.0
Master      130304.5
PhD          66445.0
Name: ConvertedComp, dtype: float64


In [18]:
# 11
import numpy as np
import pandas as pd
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

df = pd.DataFrame({
 'Name': [STUDENT_NAME]*5,
 'Score': np.random.randint(STUDENT_ID%50, STUDENT_ID%100+50,5),
 'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})

print(df)

             Name  Score  YearsCodePro
0  Gabriel Moreno     67            17
1  Gabriel Moreno     48            20
2  Gabriel Moreno     57            23
3  Gabriel Moreno     51             5
4  Gabriel Moreno     41             5


In [19]:
# 10
import numpy as np
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1

print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[-1 55 11]
 [-1 -1 -1]
 [-1 21 -1]]


In [20]:
# 9
import numpy as np
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
flat_arr = arr.flatten()
transposed_arr = arr.T

print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[30 55 11 20]
 [14  4 18 21]
 [56 38 38 23]]
Flattened: [30 55 11 20 14  4 18 21 56 38 38 23]
Transposed:
 [[30 14 56]
 [55  4 38]
 [11 18 38]
 [20 21 23]]


In [21]:
# 8
import numpy as np
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail')

print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

Gabriel Moreno's Scores: [74 83 77 62  3 81 20 37 22 47]
Grades: ['Pass' 'Pass' 'Pass' 'Fail' 'Fail' 'Pass' 'Fail' 'Fail' 'Fail' 'Fail']


In [22]:
# 7
import numpy as np
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0

print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Gabriel Moreno's Modified 4x4 Array:
 [[ 0 55  0 20]
 [14  4 18 21]
 [ 0 38  0 23]
 [48 14 47  7]]


In [23]:
# 6
import numpy as np
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838

angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)

print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

Gabriel Moreno's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [24]:
# 5
import numpy as np
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

product = A @ B
det_A = np.linalg.det(A)

print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[30 55]
 [11 20]]
Matrix B:
 [[14  4]
 [18 21]]
A @ B:
 [[1410 1275]
 [ 514  464]]
Determinant of A: -4.99999999999993


In [25]:
# 4
import numpy as np
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x>STUDENT_ID%50) & (x<STUDENT_ID%100)]

print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Gabriel Moreno's Original: [75 84 78 63  4 82 21 38 23 48]
Filtered subset: []


In [26]:
# 3
import numpy as np
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)

slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)

Gabriel Moreno's 3D Array:
 [[[22 10 19]
  [13  3 17]
  [20 23  5]]

 [[ 5 22 15]
  [13 14  6]
  [27  9 22]]

 [[27 26 20]
  [ 7  2 16]
  [16  2 11]]]
Slice[:,1,:]:
 [[13  3 17]
 [13 14  6]
 [ 7  2 16]]


In [27]:
# 2
import numpy as np
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)

row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)

print("Row sums:", row_sums)
print("Column sums:", col_sums)

Gabriel Moreno's Matrix:
 [[30 55 11 20]
 [14  4 18 21]
 [56 38 38 23]]
Row sums: [116  57 155]
Column sums: [100  97  67  64]


In [28]:
# 1
import numpy as np
STUDENT_NAME = "Gabriel Moreno"
STUDENT_ID = 838
np.random.seed(STUDENT_ID)

data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)

mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

Gabriel Moreno's Array: [75 84 78 63  4 82 21 38 23 48]
Mean: 51.6 Std Dev: 27.507089995126712
