In [11]:
# 10. DATA GROUPING AND AGGREGATION

import pandas as pd

# Create sample dataset (instead of loading CSV)
df_kaggle = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'YearsCodePro': [2, 12, 5, 15, 8],
    'ConvertedComp': [30000, 120000, 60000, 90000, 70000]
})

print("Loaded Dataset:\n", df_kaggle.head())

df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedComp']]
print("Subset of Data:\n", df_subset.head())

df_clean = df_subset.dropna()
print("Cleaned Data:\n", df_clean.head())

df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')

grouped_data = df_clean.groupby(['Country', 'ExperienceLevel'])['ConvertedComp'].mean()
print("Grouped Average Salary:\n", grouped_data.head())

grouped_data = grouped_data.reset_index()
print("Formatted Grouped Data:\n", grouped_data.head())

Loaded Dataset:
        Country   EdLevel  YearsCodePro  ConvertedComp
0  Philippines  Bachelor             2          30000
1          USA    Master            12         120000
2           UK       PhD             5          60000
3       Canada  Bachelor            15          90000
4      Germany    Master             8          70000
Subset of Data:
        Country   EdLevel  YearsCodePro  ConvertedComp
0  Philippines  Bachelor             2          30000
1          USA    Master            12         120000
2           UK       PhD             5          60000
3       Canada  Bachelor            15          90000
4      Germany    Master             8          70000
Cleaned Data:
        Country   EdLevel  YearsCodePro  ConvertedComp
0  Philippines  Bachelor             2          30000
1          USA    Master            12         120000
2           UK       PhD             5          60000
3       Canada  Bachelor            15          90000
4      Germany    Master         

In [9]:
# 9. IMPORTING AND SUMMARIZING DATA

df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame:\n", df_imported)

summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats)

print("Column Means:\n", df_imported.mean())
print("Column Standard Deviations:\n", df_imported.std())

Data saved to 'sample_data.csv'.
Imported DataFrame:
     X   Y   Z     Log_X    Sqrt_Y
0  37  13  47  3.610918  3.605551
1  34  15   7  3.526361  3.872983
2  45  46  47  3.806662  6.782330
3  46  13  46  3.828641  3.605551
4   5  44  39  1.609438  6.633250
Summary Statistics:
                X         Y          Z     Log_X    Sqrt_Y
count   5.000000   5.00000   5.000000  5.000000  5.000000
mean   33.400000  26.20000  37.200000  3.276404  4.899933
std    16.682326  17.19593  17.210462  0.940651  1.654787
min     5.000000  13.00000   7.000000  1.609438  3.605551
25%    34.000000  13.00000  39.000000  3.526361  3.605551
50%    37.000000  15.00000  46.000000  3.610918  3.872983
75%    45.000000  44.00000  47.000000  3.806662  6.633250
max    46.000000  46.00000  47.000000  3.828641  6.782330
Column Means:
 X         33.400000
Y         26.200000
Z         37.200000
Log_X      3.276404
Sqrt_Y     4.899933
dtype: float64
Column Standard Deviations:
 X         16.682326
Y         17.195930


In [8]:
# 8. NUMPY + PANDAS

import pandas as pd

data = np.random.randint(1, 50, size=(5, 3))
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data:\n", df_data)

df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data)

print("Correlation Matrix:\n", df_data.corr())

Generated Data:
     X   Y   Z
0  37  13  47
1  34  15   7
2  45  46  47
3  46  13  46
4   5  44  39
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  37  13  47  3.610918  3.605551
1  34  15   7  3.526361  3.872983
2  45  46  47  3.806662  6.782330
3  46  13  46  3.828641  3.605551
4   5  44  39  1.609438  6.633250
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000 -0.432603  0.165964  0.984647 -0.443528
Y      -0.432603  1.000000  0.269302 -0.520506  0.999786
Z       0.165964  0.269302  1.000000  0.043011  0.250230
Log_X   0.984647 -0.520506  0.043011  1.000000 -0.529320
Sqrt_Y -0.443528  0.999786  0.250230 -0.529320  1.000000


In [7]:
# 7. NUMPY FUNCTIONS

angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)

Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270]


In [6]:
# 6. STATISTICAL OPERATIONS

print("Mean experience:", np.mean(years_exp))
print("Std deviation of experience:", np.std(years_exp))
print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries))
print("Sum of all salaries:", np.sum(salaries))

Mean experience: 5.2
Std deviation of experience: 3.1240998703626617
Max salary: 100 Min salary: 50
Sum of all salaries: 450


In [5]:
# 5. BROADCASTING

bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus
print("Salaries after bonus:\n", salaries_with_bonus)

Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]]


In [4]:
# 4. RESHAPING AND DIMENSIONS

# Step 1: Reshape
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)

# Step 2: Flatten
flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

# Step 3: Transpose
print("Transposed Array:\n", reshaped_exp.T)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [3]:
# 3. INDEXING AND SLICING

# Step 1: Access individual element
print("First year of experience:", years_exp[0])

# Step 2: Slice arrays
print("First two salaries:", salaries[0, :2])

# Step 3: Access column
print("Second column salaries:", salaries[:, 1])

# Step 4: Negative indexing
print("Last year of experience:", years_exp[-1])

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [60 90]
Last year of experience: 10


In [2]:
# 2. ARRAY OPERATIONS

# Step 1: Element-wise addition
exp_plus_5 = years_exp + 5
print("Years + 5:", exp_plus_5)

# Step 2: Element-wise multiplication
exp_times_2 = years_exp * 2
print("Years * 2:", exp_times_2)

# Step 3: Dot product
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)

Years + 5: [ 6  8 10 12 15]
Years * 2: [ 2  6 10 14 20]
Dot Product: 32


In [1]:
# 1. CREATE NUMPY ARRAYS

# Step 1: Import NumPy
import numpy as np

# Step 2: Create a 1D array representing years of experience
years_exp = np.array([1, 3, 5, 7, 10])
print("Years of Experience:", years_exp)

# Step 3: Create a 2D array representing sample salaries (in thousands)
salaries = np.array([[50, 60, 70], [80, 90, 100]])
print("Salary Matrix:\n", salaries)

# Step 4: Create an array of zeros and ones for placeholder analysis
zeros_array = np.zeros((2, 2)) # 2x2 zeros
ones_array = np.ones((2, 3)) # 2x3 ones
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
